//
//  DummyPages2.swift
//  Bau gagal
//
//  Created by Ahmad Miftah Syakir on 19/04/21.
//

import UIKit
let Chara = [Hero(id: 1,photo: "Kurumi(2)", name:"Tokisaki kurumi", desription: "Kurumi Tokisaki (時とき崎さき 狂くる三み, Tokisaki Kurumi?) adalah Roh ketiga yang muncul. Karena aksinya yang brutal, dia disebut sebagai Roh Terburuk (最悪の精霊, Saiaku no Seirei?). Dia juga adalah Roh pertama yang muncul sebagai antagonis dalan seri Walaupun umurnya yang sebenarnya tidak diketahui, namun penampilan luarnya nampak masih remaja. Pada kenyataanya mungkin ia seumuran dengan si Roh Pertama. Pada saat ia menghadiri SMA Raizen, ia mengenakan seragam SMA Raizen berwarna hitam dan rok sepaha berwarna biru. Bagian bawahnya mengenakan stocking panjang warna hitam dan sepatu sekolah berwarna hitam. Rambut hitamnya tergerai dibagian belakang dan diikat model pigtail pada bagian tepi menjadi dua bagian yang diikat dengan ikat rambut berwarna coklat muda. Pada penampilannya disekolah, ia hanya menunjukkan sebagian wajahnya saja. Pada saat menjadi roh, ia mengenakan gaun gothic lolita bewarna oranye dan juga menampilkan keseluruhan wajahnya, yang dimana ia memperlihatkan iris matanya yang berbentuk seperti sebuah jam"),
Hero(id: 2,photo: "Muzan", name:"Muzan", desription: "Muzan Kibutsuji merupakan tokoh antagonis utama dalam serial Kimetsu no Yaiba . Muzan Kibutsuji merupakan iblis yang jahat, berhati dingin, dan kejam yang terobsesi menjadi makhluk yang sempurna. Ada fakta menarik Muzan Kibutsuji yang mungkin masih banyak orang belum mengatahuinya dan fakta tersebut pastinya menarik juga untuk disimak"),
Hero(id: 3,photo: "Megumin(1)", name:"Megumin", desription: "Seorang penyihir yang diturunkan dari iblis krimson; yang memiliki rambut hitam dan mata merah, serta karakteristik chūnibyō.LN 5.5 Megumin hanya mengetahui satu sihir, sebuah sihir ledakan yang sangat kuat, menyebabkan dirinya tidak bisa bergerak setelah mengeluarkan sihir tersebut. Dia menolak untuk mempelajari keterampilan lain"),
Hero(id: 4, photo: "Akame", name: "Akame", desription: "Tatsumi adalah seorang pejuang yang didampingi oleh dua teman masa kecilnya, Sayo dan Ieyasu, pergi ke ibu kota untuk mencari cara mendapatkan uang demi membantu mengentaskan kemiskinan di desanya. Setelah terpisah dengan teman-temannya karena serangan bandit, Tatsumi gagal mendaftar menjadi tentara dan harus merasakan kejamnya kehidupan di ibu kota. Hidup seperti gelandangan di jalanan, ia lalu diambil oleh keluarga bangsawan, tapi ketika sebuah kelompok pembunuh yang disebut Night Raid menyerang, dia mengetahui bahwa sang tuan rumah ternyata menyiksa dan membunuhnya seperti yang telah mereka lakukan kepada dua temannya, Sayo dan Ieyasu. Akhirnya, ia bergabung dengan Night Raid, yang terdiri dari seorang Ahli Pedang Akame; Petarung Ganas Leone; Gadis Sniper Mine; Pemegang Gunting Sheele; Pemanipulasi Benang Lubbock; Prajurit Baju Besi bernama Bulat; dan pemimpin mereka Najenda, seorang mantan jenderal angkatan darat kekaisaran yang membelot karena tak tahan melihat kekejaman pihak kerajaan pada rakyat. Night Raid juga adalah bagian dari kekuatan revolusioner yang berkumpul untuk menggulingkan perdana menteri Honest yang secara terang - terangan memanipulasi kaisar muda untuk keuntungan pribadinya meskipun seluruh bangsa jatuh dalam kemiskinan dan perselisihan.")
]
