//
//  DummyPages.swift
//  Bau gagal
//
//  Created by Ahmad Miftah Syakir on 16/04/21.
//

import UIKit

let heroes = [Hero(id: 1,photo: "Noelle", name:"Noelle", desription: "Noelle merupakan karakter berelemen Geo di Genshin Impact yang memiliki tingkat durability yang tinggi. Karena skill-nya yang terbilang biasa saja, Noelle seringkali diremehkan dan jarang digunakan. Jika menggunakan build yang benar, bisa saja Noelle menjadi DPS yang cukup mengerikan."),
Hero(id: 2,photo: "Kurumi(2)", name:"Tokisaki kurumi", desription: "Kurumi Tokisaki (時とき崎さき 狂くる三み, Tokisaki Kurumi?) adalah Roh ketiga yang muncul. Karena aksinya yang brutal, dia disebut sebagai Roh Terburuk (最悪の精霊, Saiaku no Seirei?). Dia juga adalah Roh pertama yang muncul sebagai antagonis dalan seri Walaupun umurnya yang sebenarnya tidak diketahui, namun penampilan luarnya nampak masih remaja. Pada kenyataanya mungkin ia seumuran dengan si Roh Pertama. Pada saat ia menghadiri SMA Raizen, ia mengenakan seragam SMA Raizen berwarna hitam dan rok sepaha berwarna biru. Bagian bawahnya mengenakan stocking panjang warna hitam dan sepatu sekolah berwarna hitam. Rambut hitamnya tergerai dibagian belakang dan diikat model pigtail pada bagian tepi menjadi dua bagian yang diikat dengan ikat rambut berwarna coklat muda. Pada penampilannya disekolah, ia hanya menunjukkan sebagian wajahnya saja. Pada saat menjadi roh, ia mengenakan gaun gothic lolita bewarna oranye dan juga menampilkan keseluruhan wajahnya, yang dimana ia memperlihatkan iris matanya yang berbentuk seperti sebuah jam."),
Hero(id: 3,photo: "Megumin(1)", name:"Megumin", desription: "Seorang penyihir yang diturunkan dari iblis krimson; yang memiliki rambut hitam dan mata merah, serta karakteristik chūnibyō.LN 5.5 Megumin hanya mengetahui satu sihir, sebuah sihir ledakan yang sangat kuat, menyebabkan dirinya tidak bisa bergerak setelah mengeluarkan sihir tersebut. Dia menolak untuk mempelajari keterampilan lain"),
Hero(id: 4,photo: "Muzan", name:"muzan", desription: " Muzan Kibutsuji merupakan tokoh antagonis utama dalam serial Kimetsu no Yaiba . Muzan Kibutsuji merupakan iblis yang jahat, berhati dingin, dan kejam yang terobsesi menjadi makhluk yang sempurna. Ada fakta menarik Muzan Kibutsuji yang mungkin masih banyak orang belum mengatahuinya dan fakta tersebut pastinya menarik juga untuk disimak"),
Hero(id: 5,photo: "tanjiro", name:"Tanjiro", desription: "Meskipun menderita kehilangan keluarganya dan menjadi demon slayer yang terlatih dan mapan, Tanjiro mungkin adalah karakter berhati mulia. Kebaikannya yang teguh juga merupakan bahan bakar yang kuat untuk kemarahannya, yang berfungsi sebagai kunci kekuatannya sebagai pemain pedang Tidak peduli seberapa menakutkan kekuatan musuhnya, Tanjiro bertahan dan mengingatkan para iblis untuk mengingat dan menyadari sisi manusiawi mereka. Banyak lawannya yang haus darah dapat menemukan kedamaian setelah bertemu dengan Tanjiro, menyelesaikan sakit hati yang belum terselesaikan saat masih jadi manusia sebelum akhirnya hancur jadi debu"),
Hero(id: 6,photo: "Hu tao", name:"Hu tao", desription: "Hu Tao merupakan karakter bintang lima yang mengandalkan senjata berjenis polearm. Karakter ini digambarkan sebagai gadis muda dengan status sebagai master ke-77 dari Wangsheng Funeral Parlor. Singkatnya, Hu Tao merupakan pengelola bisnis pemakaman di Liyue dalam cerita Genshin Impact"),
Hero(id: 7,photo: "elaina", name:"Elaina", desription: "Majo no Tabitabi (bahasa Jepang: 魔女の旅々) yang diterbitkan dalam bahasa Inggris dengan judul Wandering Witch: The Journey of Elaina adalah sebuah seri novel ringan Jepang yang ditulis oleh Jougi Shiraishi dan diilustrasikan oleh Azure. Penerbit SB Creative telah merilis 15 volume sejak tanggal 14 April 2016 di bawah label GA Novel milik mereka. Sebuah adaptasi manga dengan gambar oleh Itsuki Nanao telah dimuat berseri sejak tahun 2018 dalam majalah manga daring Manga UP! terbitan Square Enix dan telah dibundel menjadi tiga volume tankōbon. Seri novel ringannya dilisensikan di Amerika Utara oleh Yen Press dan untuk seri manganya dilisensikan oleh Square Enix. Sebuah adaptasi anime yang diproduksi oleh C2C ditayangkan sejak tanggal 2 Oktober 2020 hingga 18 Desember 2020."),
Hero(id: 8, photo: "Akame", name: "akame", desription: "Tatsumi adalah seorang pejuang yang didampingi oleh dua teman masa kecilnya, Sayo dan Ieyasu, pergi ke ibu kota untuk mencari cara mendapatkan uang demi membantu mengentaskan kemiskinan di desanya. Setelah terpisah dengan teman-temannya karena serangan bandit, Tatsumi gagal mendaftar menjadi tentara dan harus merasakan kejamnya kehidupan di ibu kota. Hidup seperti gelandangan di jalanan, ia lalu diambil oleh keluarga bangsawan, tapi ketika sebuah kelompok pembunuh yang disebut Night Raid menyerang, dia mengetahui bahwa sang tuan rumah ternyata menyiksa dan membunuhnya seperti yang telah mereka lakukan kepada dua temannya, Sayo dan Ieyasu. Akhirnya, ia bergabung dengan Night Raid, yang terdiri dari seorang Ahli Pedang Akame; Petarung Ganas Leone; Gadis Sniper Mine; Pemegang Gunting Sheele; Pemanipulasi Benang Lubbock; Prajurit Baju Besi bernama Bulat; dan pemimpin mereka Najenda, seorang mantan jenderal angkatan darat kekaisaran yang membelot karena tak tahan melihat kekejaman pihak kerajaan pada rakyat. Night Raid juga adalah bagian dari kekuatan revolusioner yang berkumpul untuk menggulingkan perdana menteri Honest yang secara terang - terangan memanipulasi kaisar muda untuk keuntungan pribadinya meskipun seluruh bangsa jatuh dalam kemiskinan dan perselisihan.")
]


